import type { Metadata } from 'next'
import { Inter, Overpass } from 'next/font/google'
import '../globals.css'
import { PreferencesProvider } from '@/contexts/PreferencesContext'
import Header from '@/components/Header'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin', 'cyrillic'],
})

const overpass = Overpass({
  variable: '--font-overpass',
  subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${overpass.variable} antialiased`}>
        <PreferencesProvider>
          <Header />
          {children}
        </PreferencesProvider>
      </body>
    </html>
  )
}
